language:
  - bash

before_script:
  - sudo easy_install bashtest lftp
  - sudo mkdir -p /var/www/vhosts/{alpha,beta,charlie,delta}.com
  - sudo chmod +x ./chrooter.bash
  - sudo cat ./tests/sshd_config >> /etc/ssh/sshd_config

script:
  - bashtest ./tests/username_test.bashtest
  - bashtest ./tests/ls_test.bashtest
  - bashtest ./tests/sftp_test.bashtest
