language:
  - bash

before_script:
  - sudo easy_install bashtest lftp
  - sudo mkdir -p /var/www/vhosts/{alpha,beta,charlie,delta}.com
  - sudo chmod +x ./chrooter.bash
  - sudo sed -i 's/Subsystem/# Subsystem/' /etc/ssh/sshd_config
  - sudo cat ./test/sshd_config >> /etc/ssh/sshd_config
  - sudo sshd -t
  - sudo service sshd reload

script:
  - bashtest ./test/username_test.bashtest
  - bashtest ./test/ls_test.bashtest
  - bashtest ./test/sftp_test.bashtest
